<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class OpcionesTriptico {
	private $opciones_triptico_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'opciones_triptico_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'opciones_triptico_page_init' ) );
	}

	public function opciones_triptico_add_plugin_page() {
		add_menu_page(
			'Opciones triptico', // page_title
			'Opciones triptico', // menu_title
			'manage_options', // capability
			'opciones-triptico', // menu_slug
			array( $this, 'opciones_triptico_create_admin_page' ), // function
			'dashicons-art', // icon_url
			2 // position
		);
	}

	public function opciones_triptico_create_admin_page() {
		$this->opciones_triptico_options = get_option( 'opciones_triptico_option_name' ); ?>

		<div class="wrap">
			<h2>Opciones triptico</h2>
			<p>Información adicional para sitio Tríptico</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'opciones_triptico_option_group' );
					do_settings_sections( 'opciones-triptico-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function opciones_triptico_page_init() {
		register_setting(
			'opciones_triptico_option_group', // option_group
			'opciones_triptico_option_name', // option_name
			array( $this, 'opciones_triptico_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'opciones_triptico_setting_section', // id
			'Settings', // title
			array( $this, 'opciones_triptico_section_info' ), // callback
			'opciones-triptico-admin' // page
		);

		add_settings_field(
			'descripcin_secundaria_para_pgina_de_inicio_0', // id
			'Descripción secundaria para página de inicio', // title
			array( $this, 'descripcin_secundaria_para_pgina_de_inicio_0_callback' ), // callback
			'opciones-triptico-admin', // page
			'opciones_triptico_setting_section' // section
		);

		add_settings_field(
			'descripcin_secundaria_para_pgina_de_inicio_english_1', // id
			'Descripción secundaria para página de inicio (english)', // title
			array( $this, 'descripcin_secundaria_para_pgina_de_inicio_english_1_callback' ), // callback
			'opciones-triptico-admin', // page
			'opciones_triptico_setting_section' // section
		);

		add_settings_field(
			'id_pagina_no_encontrada', // id
			'ID de la página no encontrada', // title
			array( $this, 'id_pagina_no_encontrada_callback' ), // callback
			'opciones-triptico-admin', // page
			'opciones_triptico_setting_section' // section
		);

		add_settings_field(
			'link_2', // id
			'Link', // title
			array( $this, 'link_2_callback' ), // callback
			'opciones-triptico-admin', // page
			'opciones_triptico_setting_section' // section
		);
	}

	public function opciones_triptico_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['descripcin_secundaria_para_pgina_de_inicio_0'] ) ) {
			$sanitary_values['descripcin_secundaria_para_pgina_de_inicio_0'] = esc_textarea( $input['descripcin_secundaria_para_pgina_de_inicio_0'] );
		}

		if ( isset( $input['descripcin_secundaria_para_pgina_de_inicio_english_1'] ) ) {
			$sanitary_values['descripcin_secundaria_para_pgina_de_inicio_english_1'] = esc_textarea( $input['descripcin_secundaria_para_pgina_de_inicio_english_1'] );
		}

		if( isset( $input['id_pagina_no_encontrada']) ) {
			$sanitary_values['id_pagina_no_encontrada'] = sanitize_text_field( $input['id_pagina_no_encontrada']);
		}

		if ( isset( $input['link_2'] ) ) {
			$sanitary_values['link_2'] = sanitize_text_field( $input['link_2'] );
		}

		return $sanitary_values;
	}

	public function opciones_triptico_section_info() {
		
	}

	public function descripcin_secundaria_para_pgina_de_inicio_0_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="opciones_triptico_option_name[descripcin_secundaria_para_pgina_de_inicio_0]" id="descripcin_secundaria_para_pgina_de_inicio_0">%s</textarea>',
			isset( $this->opciones_triptico_options['descripcin_secundaria_para_pgina_de_inicio_0'] ) ? esc_attr( $this->opciones_triptico_options['descripcin_secundaria_para_pgina_de_inicio_0']) : ''
		);
	}

	public function descripcin_secundaria_para_pgina_de_inicio_english_1_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="opciones_triptico_option_name[descripcin_secundaria_para_pgina_de_inicio_english_1]" id="descripcin_secundaria_para_pgina_de_inicio_english_1">%s</textarea>',
			isset( $this->opciones_triptico_options['descripcin_secundaria_para_pgina_de_inicio_english_1'] ) ? esc_attr( $this->opciones_triptico_options['descripcin_secundaria_para_pgina_de_inicio_english_1']) : ''
		);
	}

	public function link_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="opciones_triptico_option_name[link_2]" id="link_2" value="%s">',
			isset( $this->opciones_triptico_options['link_2'] ) ? esc_attr( $this->opciones_triptico_options['link_2']) : ''
		);
	}

	public function id_pagina_no_encontrada_callback() {
		printf(
			'<input class="regular-text" type="text" name="opciones_triptico_option_name[id_pagina_no_encontrada]" id="id_pagina_no_encontrada" value="%s">',
			isset( $this->opciones_triptico_options['id_pagina_no_encontrada'] ) ? esc_attr( $this->opciones_triptico_options['id_pagina_no_encontrada']) : ''
		);
	}

}
if ( is_admin() )
	$opciones_triptico = new OpcionesTriptico();

/* 
 * Retrieve this value with:
 * $opciones_triptico_options = get_option( 'opciones_triptico_option_name' ); // Array of All Options
 * $descripcin_secundaria_para_pgina_de_inicio_0 = $opciones_triptico_options['descripcin_secundaria_para_pgina_de_inicio_0']; // Descripción secundaria para página de inicio
 * $descripcin_secundaria_para_pgina_de_inicio_english_1 = $opciones_triptico_options['descripcin_secundaria_para_pgina_de_inicio_english_1']; // Descripción secundaria para página de inicio (english)
 * $link_2 = $opciones_triptico_options['link_2']; // Link
 */
